### PR TITLE
fix(bool-with-inverse-flag): fix string printing of bool with inverse flag to properly show inverse prefix

### LINKED ISSUE #1883: How do I define Usage for BoolWithInverseFlag?
I defined a "summary" boolean flag as a `BoolWithInverseFlag`.

But the help/usage text doesn't look very helpful to me:

```go
package main

import (
	"context"

	"github.com/urfave/cli/v3"
)

func main() {
	cmd := &cli.Command{
		Name:                   "sendsomething",
		Usage:                  "report some stuff",
		ArgsUsage:              "",
		HideHelpCommand:        true,
		UseShortOptionHandling: true,
		Flags: []cli.Flag{
			&cli.BoolFlag{
				Name:    "verbose",
				Aliases: []string{"v"},
				Usage:   "Show more output.",
			},
			&cli.BoolFlag{
				Name:    "dry-run",
				Aliases: []string{"dryrun", "d"},
				Usage:   "Do a dry-run.",
			},
			&cli.StringSliceFlag{
				Name:  "to",
				Usage: "Define alternative recipients.",
			},
			&cli.BoolWithInverseFlag{
				BoolFlag: &cli.BoolFlag{
					Name:  "summary",
					Usage: "default is, to send a summary to all subscribers.",
				},
			},
		},
	}
	_ = cmd.Run(context.Background(), []string{"prog", "--help"})
}
```

[See on Go Playground](https://play.golang.com/p/c-Mu2cSv4pd)

### Actual output

```
NAME:
   sendsomething - report some stuff

USAGE:
   sendsomething [global options] [arguments...]

GLOBAL OPTIONS:
   --verbose, -v              Show more output. (default: false)
   --dry-run, --dryrun, -d    Do a dry-run. (default: false)
   --to value [ --to value ]  Define alternative recipients.
   --summary                  default is, to send a summary to all subscribers. (default: false) || --no-summary  default is, to send a summary to all subscribers. (default: false)
   --help, -h                 show help (default: false)
```

### Expected output

This is the output I expected:

```
NAME:
   sendsomething - report some stuff

USAGE:
   sendsomething [global options] [arguments...]

GLOBAL OPTIONS:
   --verbose, -v              Show more output. (default: false)
   --dry-run, --dryrun, -d    Do a dry-run. (default: false)
   --to value [ --to value ]  Define alternative recipients.
   --summary                  Only send the summary. (default: false)
   --no-summary               Suppress the default summary. (default: false)
   --help, -h                 show help (default: false)
```

So far, with my current knowledge, I can only achieve it by defining two separate `BoolFlag`s, which is an ugly workaround.

Am I misundertstanding the BoolWithInverseFlag? Am I using it wrong?

### PR DESCRIPTION
**Pull request by mahadzaryab1**
## What type of PR is this?

- bug
## What this PR does / why we need it:

- The current usage output of the `BoolWithInverseFlag` was confusing as it was outputting the same description for both the positive and negative flags. This PR makes the usage a bit more clear by only printing out one usage description and printing the inverse prefix in brackets. 

## Which issue(s) this PR fixes:

This PR fixes #1883. 

## Special notes for your reviewer:

- I tried to make the fix using the existing `FlagStringer` and manipulating its output to match what we want. Let me know if you'd like to use a different approach here however!

## Testing

- Added unit tests for changes

## Release Notes

```release-note
Fixed the usage description of a `BoolWithInverseFlag` to show the inverse prefix in square brackets. 
For example: --[no-]env	(default: false)
```

### CODE REVIEW

File: flag_bool_with_inverse.go [hunk 1]
```diff
@@ -123,6 +123,14 @@ func (parent *BoolWithInverseFlag) inverseName() string {
 	return parent.InversePrefix + parent.BoolFlag.Name
 }
 
+func (parent *BoolWithInverseFlag) inversePrefix() string {
```
Comment (dearchap) [inline flag_bool_with_inverse.go:126]: Can you add some test cases for this ? i.e setting InversePrefix to something else ?

File: flag_bool_with_inverse.go [hunk 2]
```diff
@@ -170,11 +178,15 @@ func (parent *BoolWithInverseFlag) Names() []string {
...
-// --env     (default: false) || --no-env    (default: false)
+// --[no-]env	(default: false)
 func (parent *BoolWithInverseFlag) String() string {
-	if parent.positiveFlag == nil {
-		return fmt.Sprintf("%s || --%s", parent.BoolFlag.String(), parent.inverseName())
+	out := FlagStringer(parent)
+	i := strings.Index(out, "\t")
+
+	// single character flags are prefixed with `-` instead of `--`
+	if len(parent.Name) == 1 {
```
Comment (dearchap) [inline flag_bool_with_inverse.go:187]:
```suggestion
       prefix := "--"
 	if len(parent.Name) == 1 {
 	    prefix = "-"
 	 }
 	 return fmt.Sprintf("%s[%s]%s%s", prefix, parent.inversePrefix(), parent.Name, out[i:])
	}
 	 
 	 
```

File: flag_bool_with_inverse_test.go [hunk 3]
```diff
@@ -334,10 +334,87 @@ func TestBoolWithInverseNames(t *testing.T) {
...
-	require.Contains(t, flagString, "--no-env")
+	for _, tc := range tcs {
+		t.Run(tc.testName, func(t *testing.T) {
+			flag := &BoolWithInverseFlag{
+				BoolFlag: &BoolFlag{
+					Name:     tc.flagName,
+					Usage:    tc.usage,
+					Required: tc.required,
+				},
+			}
```
Comment (dearchap) [inline flag_bool_with_inverse_test.go:409]:
```suggestion
      InversePrefix: tc.InversePrefix,
	}
```
This will remove the test coverage warning above !!!!

**Review by dearchap — APPROVED** [review]
Thanks @mahadzaryab1
