### PR TITLE
Fix linting issues

### LINKED ISSUE #1663: Add integration with golangci-lint
The [golangci-lint](https://golangci-lint.run/) meta-linting tool is widely used to ensure various classes of bugs and maintenance hindrances stay out of the code. Introducing this tool will almost certainly result in a lot of warnings and errors, so I'm happy to consider a _gradual adoption_ via config file tweaking.

### PR DESCRIPTION
**Pull request by skelouse**
## What type of PR is this?

- cleanup

## What this PR does / why we need it:

Fixes 100% of `golangci-lint` linting issues

## Which issue(s) this PR fixes:

Partially fixes #1663 

## Testing

https://asciinema.org/a/ucDYTAfRZzASFpkmpfdrTxQHJ

ran make

## Release Notes
```release-note
Update to pass `golangci-lint`
```

### CODE REVIEW

**Comment by skelouse** [comment]
Can we override the patch diff, or should I add test cases for the error checks?

File: flag_test.go [hunk 1]
```diff
@@ -426,7 +426,11 @@ func TestStringFlagHelpOutput(t *testing.T) {
 		fl := &StringFlag{Name: test.name, Aliases: test.aliases, Usage: test.usage, Value: test.value}
 		// create a tmp flagset
 		tfs := flag.NewFlagSet("test", 0)
-		fl.Apply(tfs)
+		err := fl.Apply(tfs)
+		if err != nil {
+			t.Error(err)
+			return
+		}
```
Comment (meatballhat) [inline flag_test.go:433]: I'm happy to start using `stretchr/testify` more around here, e.g.:

```suggestion
		require.Nil(t, fl.Apply(tfs))
```

File: help.go [hunk 2]
```diff
@@ -352,27 +363,32 @@ func printHelpCustom(out io.Writer, templ string, data interface{}, customFuncs
...
+	handleTemplateError(err)
+	_, err = t.New("visibleGlobalFlagCategoryTemplate").Parse(strings.Replace(visibleFlagCategoryTemplate, "OPTIONS", "GLOBAL OPTIONS", -1))
+	handleTemplateError(err)
+	_, err = t.New("authorsTemplate").Parse(authorsTemplate)
+	handleTemplateError(err)
+	_, err = t.New("visibleCommandCategoryTemplate").Parse(visibleCommandCategoryTemplate)
+	handleTemplateError(err)
+
+	err = t.Execute(w, data)
+	handleTemplateError(err)
```
Comment (meatballhat) [inline help.go:390]: imho this is a great place to use the "iferr" form so that the `err` var isn't getting overwritten and adding to the potential for unexpected debug output, and the last case can be folded up without assigning `err` at all 👍🏼

**Review by meatballhat — DISMISSED** [review]
Overall I'm very excited about this change! Thank you @skelouse 🎉 

- the notes here don't need to be addressed in this PR, but I'd like to get them done soonish
- ignoring the patch-level coverage check is fine in this case, imho
- can either this PR or a near future follow-up PR add `golangci-lint` integration in CI to assert that new linting errors are not introduced?

File: completion.go [hunk 3]
```diff
@@ -54,7 +54,10 @@ var completionCommand = &Command{
 		} else if c, err := rc(ctx.App); err != nil {
 			return Exit(err, 1)
 		} else {
-			ctx.App.Writer.Write([]byte(c))
+			_, err = ctx.App.Writer.Write([]byte(c))
+			if err != nil {
+				return Exit(err, 1)
+			}
```
[the remark this answers is not in the document]
Comment (meatballhat) [reply completion.go:60]: 🤦🏼 this is targeting the v3 alpha, so never mind what I said! Let's exit non-zero on failure to write completion 👍🏼

File: context_test.go [hunk 4]
```diff
@@ -281,7 +281,11 @@ func TestContext_Set_InvalidFlagAccessHandler(t *testing.T) {
 		},
 	}
 	c := NewContext(app, set, nil)
-	c.Set("missing", "")
+	err := c.Set("missing", "")
+	if err == nil {
```
Comment (dearchap) [inline context_test.go:285]: can we add a expectNotNil helper function for this kind of stuff ?

File: help.go [hunk 5]
```diff
@@ -352,27 +363,32 @@ func printHelpCustom(out io.Writer, templ string, data interface{}, customFuncs
...
-	err := t.Execute(w, data)
-	if err != nil {
-		// If the writer is closed, t.Execute will fail, and there's nothing
-		// we can do to recover.
-		if os.Getenv("CLI_TEMPLATE_ERROR_DEBUG") != "" {
-			_, _ = fmt.Fprintf(ErrWriter, "CLI TEMPLATE ERROR: %#v\n", err)
-		}
-		return
-	}
+	_, err := t.New("helpNameTemplate").Parse(helpNameTemplate)
```
Comment (dearchap) [inline help.go:366]: better to do 

`
if _, err := t.New(...); err != nil {
 handleTemplateError(err)
}
`

File: completion.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (skelouse) [reply completion.go]: Can easily do _, _ for v2 and support linting just the same, good note.

**Comment by skelouse** [comment]
@meatballhat  
> * can either this PR or a near future follow-up PR add `golangci-lint` integration in CI to assert that new linting errors are not introduced?

I'd love to make this change, but i'm not sure where to start with CI integrations.

File: flag_test.go (hunk 1 above)
Comment (skelouse) [reply flag_test.go]: Do we want to introduce another import in go.mod?  From my perspective it seems that this package has very few external imports.  Maybe in another PR as there are many use cases for using testify.

Comment (skelouse) [reply flag_test.go]: https://github.com/urfave/cli/issues/1695

File: completion.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (skelouse) [reply completion.go]: https://github.com/urfave/cli/pull/1696

**Review by meatballhat — APPROVED** [review]
