### PR TITLE
Fish completions with identically named sub-commands now work

### LINKED ISSUE #2115: v3 fish completions conflate 2+ level subcommand options
## My urfave/cli version is

https://github.com/urfave/cli/commit/c6c5804ca57ab98c6c209098df309403edd3c33a

## Checklist

- [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v3 manual is [here](https://cli.urfave.org/v3/getting-started/)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Describe the bug

Where a command has identical L2 sub-commands, we will suggest the union of their options.

## To reproduce

```go
	app := &cli.Command{
		Name:                  "mycli",
		Version:               "1.0.0",
		Usage:                 "Pure awesomeness.",
		EnableShellCompletion: true,
		Suggest:               true,
		Commands: []*cli.Command{
			{
				Name:  "more-awesome",
				Usage: "Become awesomer!",
				Action: func(ctx context.Context, cmd *cli.Command) error {
					return nil
				},
				Commands: []*cli.Command{
					{
						Name: "set",
						Flags: []cli.Flag{
							&cli.IntFlag{
								Name:     "increase",
								Required: true,
							},
						},
					},
				},
			},
			{
				Name:  "less-awesome",
				Usage: "Humility",
				Action: func(ctx context.Context, cmd *cli.Command) error {
					return nil
				},
				Commands: []*cli.Command{
					{
						Name: "set",
						Flags: []cli.Flag{
							&cli.IntFlag{
								Name:     "decrease",
								Required: true,
							},
						},
					},
				},
			},
		},
	}
```

## Observed behavior

```
$ mycli more-awesome set --
--decrease  --help  (show help)  --increase
```

## Expected behavior

L2 sub-commands should suggest their own options only.

## Want to fix this yourself?

The fix is to tell `complete` about the full sub-command "path". Should be straight-forward given the `Lineage()` method on commands. PR pending.

## Run `go version` and paste its output here

```
go version go1.23.8 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/andqvi/.cache/go-build'
GOENV='/home/andqvi/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/andqvi/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/andqvi/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/andqvi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.8.linux-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/andqvi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.8.linux-amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.8'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/andqvi/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/andqvi/projects/external/harness-cli/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build320049062=/tmp/go-build -gno-record-gcc-switches'
```

### PR DESCRIPTION
**Pull request by bittrance**
## What type of PR is this?

- bug

## What this PR does / why we need it:

Previously, completions for `foo bar --` and `baz bar --` would include flags from both sub-commands because they would only match on "bar". This is now fixed by including the full ancestry in the complete instructions.

## Which issue(s) this PR fixes:

Fixes #2115.

## Testing

Before:
```shell
$ mycli more-awesome set -- <tab>
--decrease  --help  (show help)  --increase
$ mycli less-awesome set -- <tab>
--decrease  --help  (show help)  --increase
```

After:
```shell
$ mycli more-awesome set -- <tab>
--help  (show help)  --increase
$ mycli less-awesome set -- <tab>
--decrease  --help  (show help)
```

## Release Notes

```release-note
Fish completions no longer conflate options from identically-named sub-commands.
```

### CODE REVIEW

File: fish.go [hunk 1]
```diff
@@ -163,14 +165,28 @@ func fishSubcommandHelper(binary string, command *Command, siblings []*Command)
...
+	ancestors = ancestors[1:]
+	for _, ancestor := range ancestors {
+		ancestry = append(
+			ancestry,
+			fmt.Sprintf(
+				"__fish_seen_subcommand_from %s",
+				strings.Join(ancestor.Names(), " "),
+			),
+		)
+	}
```
Comment (Juneezee) [inline fish.go:186]: I think it is simpler to use a reverse loop.

```suggestion
	for i := len(ancestors) - 2; i >= 0; i-- {
		ancestry = append(
			ancestry,
			fmt.Sprintf(
				"__fish_seen_subcommand_from %s",
				strings.Join(ancestors[i].Names(), " "),
			),
		)
	}
```

**Review by dearchap — APPROVED** [review]
