### PR TITLE
Fix:(issue 1689) Match markdown output with help output

### LINKED ISSUE #1689: App.ToMan() and App.ToMarkdown() don't respect DefaultText
## My urfave/cli version is

v2.24.4

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

When using `App.ToMan()` or `App.ToMarkdown()`, the generated text uses the `Value` of a flag no matter if `DefaultText` is specified or not. This makes it inconsistent to the output of the help command.

## To reproduce

Include a flag like the following in your app:

```go
&cli.StringFlag{
  Name:        "foo",
  Value:       "default value"
  DefaultText: "default text"
}
```

## Observed behavior

```shell
./main help
```

```
--foo (default: default text)
```

```go
x, _ := App.ToMan()
fmt.Println(x)
```

```
...
\fB--foo\fP="": (default: default value)
...
```

```go
x, _ := App.ToMarkdown()
fmt.Println(x)
```

```
...
**--foo**="": (default: default value)
....
```

## Expected behavior

```
...
\fB--foo\fP="": (default: default text)
...
```

```
**--foo**="": (default: default text)
```

## Additional context

None.

## Want to fix this yourself?

If confirmed, I'd be happy to fix it.

## Run `go version` and paste its output here

```
go version go1.19.6 darwin/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/path/to/Library/Caches/go-build"
GOENV="/path/to/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/path/to/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/path/to/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.19.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.6/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/path/to/example/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/path/to/go-build3156486010=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #1689 

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

make test

## Release Notes

_(REQUIRED)_

```release-note

```

### CODE REVIEW

File: fish_test.go [hunk 1]
```diff
@@ -27,11 +27,12 @@ func testApp() *App {
...
-			Name:      "socket",
-			Aliases:   []string{"s"},
-			Usage:     "some 'usage' text",
-			Value:     "value",
-			TakesFile: true,
+			Name:        "socket",
+			Aliases:     []string{"s"},
+			Usage:       "some 'usage' text",
+			Value:       "value",
+			DefaultText: "svalue",
```
Comment (abitrolly) [inline fish_test.go:34]: `svalue`?

Comment (dearchap) [reply fish_test.go:34]: Just an arbitrary string different than Value

Comment (abitrolly) [reply fish_test.go:34]:
```suggestion
			DefaultText: "some default string",
```
