### PR TITLE
Fix linting issues

### LINKED ISSUE #1663: Add integration with golangci-lint
The [golangci-lint](https://golangci-lint.run/) meta-linting tool is widely used to ensure various classes of bugs and maintenance hindrances stay out of the code. Introducing this tool will almost certainly result in a lot of warnings and errors, so I'm happy to consider a _gradual adoption_ via config file tweaking.

### PR DESCRIPTION
**Pull request by skelouse**
## What type of PR is this?

- cleanup

## What this PR does / why we need it:

Fixes 100% of `golangci-lint` linting issues

## Which issue(s) this PR fixes:

Partially fixes #1663 

## Testing

Run linter: https://asciinema.org/a/dK8y5ptbzIA9raNJpT1UPIsuY

Ran make

## Release Notes

```release-note
Update to pass `golangci-lint`
```

### CODE REVIEW

File: context_test.go [hunk 1]
```diff
@@ -292,7 +292,7 @@ func TestContext_Set_InvalidFlagAccessHandler(t *testing.T) {
 		},
 	}
 	c := NewContext(app, set, nil)
-	c.Set("missing", "")
+	expect(t, c.Set("missing", "") != nil, true)
```
Comment (skelouse) [inline context_test.go:295]: Quick note, this is a difference between v2/v3:

https://github.com/urfave/cli/pull/1694/files#diff-e6ce689a25eaef174c2dd51fe869fabbe04a6c6afbd416b23eda138c82e761baR285

**Comment by skelouse** [comment]
@urfave/cli

File: flag_test.go [hunk 2]
```diff
@@ -488,7 +488,7 @@ func TestStringFlagHelpOutput(t *testing.T) {
 		fl := &StringFlag{Name: test.name, Aliases: test.aliases, Usage: test.usage, Value: test.value}
 		// create a tmp flagset
 		tfs := flag.NewFlagSet("test", 0)
-		fl.Apply(tfs)
+		_ = fl.Apply(tfs)
```
Comment (dearchap) [inline flag_test.go:491]: No need to check err return here ?

File: altsrc/flag.go [hunk 3]
```diff
@@ -109,10 +109,10 @@ func (f *StringSliceFlag) ApplyInputSourceValue(cCtx *cli.Context, isc InputSour
 				continue
 			}
 			underlyingFlag.Value = &sliceValue
-			f.set.Set(n, sliceValue.Serialize())
+			_ = f.set.Set(n, sliceValue.Serialize())
```
Comment (dearchap) [inline altsrc/flag.go:112]: Lets check the err value explicity and return

File: altsrc/flag.go [hunk 4]
```diff
@@ -109,10 +109,10 @@ func (f *StringSliceFlag) ApplyInputSourceValue(cCtx *cli.Context, isc InputSour
...
 		}
 		if f.Destination != nil {
-			f.Destination.Set(sliceValue.Serialize())
+			_ = f.Destination.Set(sliceValue.Serialize())
```
Comment (dearchap) [inline altsrc/flag.go:115]: Lets check the err value explicity and return

File: altsrc/flag.go [hunk 5]
```diff
@@ -143,7 +143,7 @@ func (f *IntSliceFlag) ApplyInputSourceValue(cCtx *cli.Context, isc InputSourceC
 			underlyingFlag.Value = &sliceValue
 		}
 		if f.Destination != nil {
-			f.Destination.Set(sliceValue.Serialize())
+			_ = f.Destination.Set(sliceValue.Serialize())
```
Comment (dearchap) [inline altsrc/flag.go:146]: Lets check the err value explicity and return

File: altsrc/flag.go [hunk 6]
```diff
@@ -174,7 +174,7 @@ func (f *Int64SliceFlag) ApplyInputSourceValue(cCtx *cli.Context, isc InputSourc
...
```
Comment (dearchap) [inline altsrc/flag.go:177]: Lets check the err value explicity and return

File: altsrc/flag.go [hunk 7]
```diff
@@ -205,7 +205,7 @@ func (f *Float64SliceFlag) ApplyInputSourceValue(cCtx *cli.Context, isc InputSou
...
```
Comment (dearchap) [inline altsrc/flag.go:208]: Lets check the err value explicity and return

File: help.go [hunk 8]
```diff
@@ -363,17 +363,17 @@ func printHelpCustom(out io.Writer, templ string, data interface{}, customFuncs
...
-	t.New("descriptionTemplate").Parse(descriptionTemplate)
-	t.New("visibleCommandTemplate").Parse(visibleCommandTemplate)
-	t.New("copyrightTemplate").Parse(copyrightTemplate)
-	t.New("versionTemplate").Parse(versionTemplate)
-	t.New("visibleFlagCategoryTemplate").Parse(visibleFlagCategoryTemplate)
-	t.New("visibleFlagTemplate").Parse(visibleFlagTemplate)
-	t.New("visibleGlobalFlagCategoryTemplate").Parse(strings.Replace(visibleFlagCategoryTemplate, "OPTIONS", "GLOBAL OPTIONS", -1))
-	t.New("authorsTemplate").Parse(authorsTemplate)
-	t.New("visibleCommandCategoryTemplate").Parse(visibleCommandCategoryTemplate)
+	_, _ = t.New("helpNameTemplate").Parse(helpNameTemplate)
```
Comment (dearchap) [inline help.go:366]: lets define a 

`
templates := map[string]string {
  "helpNameTemplate":helpNameTemplate,
....
}
`
and iterate over the loop. Within the loop check the err return value of Parse() and panic/return

File: internal/build/build.go [hunk 9]
```diff
@@ -178,7 +178,7 @@ func sh(exe string, args ...string) (string, error) {
 
 func topRunAction(arg string, args ...string) cli.ActionFunc {
 	return func(cCtx *cli.Context) error {
-		os.Chdir(cCtx.Path("top"))
+		_ = os.Chdir(cCtx.Path("top"))
```
Comment (dearchap) [inline internal/build/build.go:181]:
```
if err := os.Chdir(...); err != nil {
   return err
}
```

File: internal/build/build.go [hunk 10]
```diff
@@ -528,13 +528,13 @@ func YAMLFmtActionFunc(cCtx *cli.Context) error {
 		return err
 	}
 
-	os.Chdir(cCtx.Path("top"))
+	_ = os.Chdir(cCtx.Path("top"))
```
Comment (dearchap) [inline internal/build/build.go:531]: Check return value and return

**Review by dearchap — CHANGES_REQUESTED** [review]
@skelouse Thanks for the changes. Can you update as per my comments. Appreciate it.

File: altsrc/flag.go (hunk 3 above)
Comment (skelouse) [reply altsrc/flag.go:112]: Issue with checking error return is potential backward compatability issues.

File: help.go (hunk 8 above)
Comment (skelouse) [reply help.go:366]: May effect backward compatability.

**Comment by skelouse** [comment]
> @skelouse Thanks for the changes. Can you update as per my comments. Appreciate it. 

I commented on some, checking errors outside of tests that have always been ignored could introduce backward compatability issues.  Thanks for the review!

File: altsrc/flag.go (hunk 3 above)
Comment (dearchap) [reply altsrc/flag.go:112]: If none of the tests fail. I would said lets check it.

File: flag_test.go (hunk 2 above)
Comment (skelouse) [reply flag_test.go:491]: 44 instances of this in flag_test.go: 
image

File: altsrc/flag.go [hunk 11]
```diff
@@ -79,7 +79,9 @@ func (f *GenericFlag) ApplyInputSourceValue(cCtx *cli.Context, isc InputSourceCo
 			continue
 		}
 		for _, n := range f.Names() {
-			_ = f.set.Set(n, value.String())
+			if err := f.set.Set(n, value.String()); err != nil {
```
Comment (dearchap) [inline altsrc/flag.go:82]: can you add a simple test case in altsrc for this ?

File: altsrc/flag.go [hunk 12]
```diff
@@ -109,10 +111,14 @@ func (f *StringSliceFlag) ApplyInputSourceValue(cCtx *cli.Context, isc InputSour
 				continue
 			}
 			underlyingFlag.Value = &sliceValue
-			f.set.Set(n, sliceValue.Serialize())
+			if err := f.set.Set(n, sliceValue.Serialize()); err != nil {
```
Comment (dearchap) [inline altsrc/flag.go:114]: can you add a simple test case in altsrc for this ?

Comment (skelouse) [reply altsrc/flag.go:114]: I don't think this is reachable, as it has to be set to get to this point.

**Review by dearchap — APPROVED** [review]
