### PR TITLE
flag: remove dependencies on shared variables

### LINKED ISSUE #1670: Race condition on disableSliceFlagSeparator in flag.go
## My urfave/cli version is

`github.com/urfave/cli/v2 v2.24.1`

## Checklist

- [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [X] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

Running integration tests by passing fake command line arguments to `.RunContext()`. Allows test to use assertion instead of `exec` an binary.

## To reproduce

1. A function is used to create a clean `*cli.Command` every time:
```go
func Generate() *cli.Command {
	return &cli.Command{
		Name:  "server",
// [...]
```
2. A helper function is used to compile into an `*cli.App`:
```go
func compileApp(cmd *cli.Command) (*cli.App, *observer.ObservedLogs) {
	observedZapCore, observedLogs := observer.New(zap.DebugLevel)
	observedLogger := zap.New(observedZapCore)
	return &cli.App{
		Name: "specter",
		Commands: []*cli.Command{
			cmd,
		},
		Before: func(ctx *cli.Context) error {
			ctx.App.Metadata["logger"] = observedLogger
			return nil
		},
		Metadata: make(map[string]interface{}),
	}, observedLogs
}
// [...]
```
3. Then create servers dynamically in test:
```go
	serverReturnCtx, serverStopped := context.WithCancel(ctx)
	defer serverStopped()

	t.Logf("Starting servers\n")

	serverLogs := make([]*observer.ObservedLogs, len(serverPorts))
	for i, args := range serverArgs {
		sApp, sLogs := compileApp(server.Generate())
		serverLogs[i] = sLogs
		args := args
		go func(app *cli.App) {
			if err := app.RunContext(ctx, args); err != nil {
				as.NoError(err)
			}
			serverStopped()
		}(sApp)
	}

	t.Logf("Waiting for servers to be started\n")
// [helper function not shown: checking if servers are started]
```
4. Then start the test:
`GO_RUN_INTEGRATION=1 go test -v -timeout 30s ./integrations -v -race`

## Observed behavior

```
==================
WARNING: DATA RACE
Write at 0x000001bb3d53 by goroutine 11:
  github.com/urfave/cli/v2.(*App).Setup()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:270 +0x1764
  github.com/urfave/cli/v2.(*App).RunContext()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:317 +0x7a
  kon.nect.sh/specter/integrations.TestTunnel.func3()
      /home/rachel/code/specter/integrations/tunnel_test.go:164 +0x88
  kon.nect.sh/specter/integrations.TestTunnel.func13()
      /home/rachel/code/specter/integrations/tunnel_test.go:168 +0x47

Previous write at 0x000001bb3d53 by goroutine 10:
  github.com/urfave/cli/v2.(*App).Setup()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:270 +0x1764
  github.com/urfave/cli/v2.(*App).RunContext()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:317 +0x7a
  kon.nect.sh/specter/integrations.TestTunnel.func3()
      /home/rachel/code/specter/integrations/tunnel_test.go:164 +0x88
  kon.nect.sh/specter/integrations.TestTunnel.func13()
      /home/rachel/code/specter/integrations/tunnel_test.go:168 +0x47

Goroutine 11 (running) created at:
  kon.nect.sh/specter/integrations.TestTunnel()
      /home/rachel/code/specter/integrations/tunnel_test.go:163 +0x2689
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47

Goroutine 10 (running) created at:
  kon.nect.sh/specter/integrations.TestTunnel()
      /home/rachel/code/specter/integrations/tunnel_test.go:163 +0x2689
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47
==================
==================
WARNING: DATA RACE
Write at 0x000001b74e30 by goroutine 11:
  github.com/urfave/cli/v2.(*BoolFlag).Apply()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/flag_bool.go:107 +0x84
  github.com/urfave/cli/v2.flagSet()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/flag.go:174 +0x25b
  github.com/urfave/cli/v2.(*Command).newFlagSet()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:278 +0xc9
  github.com/urfave/cli/v2.(*Command).parseFlags()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:311 +0x5a
  github.com/urfave/cli/v2.(*Command).Run()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:152 +0x14c
  github.com/urfave/cli/v2.(*App).RunContext()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:333 +0x10e4
  kon.nect.sh/specter/integrations.TestTunnel.func3()
      /home/rachel/code/specter/integrations/tunnel_test.go:164 +0x88
  kon.nect.sh/specter/integrations.TestTunnel.func13()
      /home/rachel/code/specter/integrations/tunnel_test.go:168 +0x47

Previous write at 0x000001b74e30 by goroutine 10:
  github.com/urfave/cli/v2.(*BoolFlag).Apply()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/flag_bool.go:107 +0x84
  github.com/urfave/cli/v2.flagSet()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/flag.go:174 +0x25b
  github.com/urfave/cli/v2.(*Command).newFlagSet()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:278 +0xc9
  github.com/urfave/cli/v2.(*Command).parseFlags()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:311 +0x5a
  github.com/urfave/cli/v2.(*Command).Run()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:152 +0x14c
  github.com/urfave/cli/v2.(*App).RunContext()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:333 +0x10e4
  kon.nect.sh/specter/integrations.TestTunnel.func3()
      /home/rachel/code/specter/integrations/tunnel_test.go:164 +0x88
  kon.nect.sh/specter/integrations.TestTunnel.func13()
      /home/rachel/code/specter/integrations/tunnel_test.go:168 +0x47

Goroutine 11 (running) created at:
  kon.nect.sh/specter/integrations.TestTunnel()
      /home/rachel/code/specter/integrations/tunnel_test.go:163 +0x2689
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47

Goroutine 10 (running) created at:
  kon.nect.sh/specter/integrations.TestTunnel()
      /home/rachel/code/specter/integrations/tunnel_test.go:163 +0x2689
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47
==================
==================
WARNING: DATA RACE
Read at 0x000001b75b28 by goroutine 11:
  github.com/urfave/cli/v2.(*Command).setup()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:133 +0x8d6
  github.com/urfave/cli/v2.(*Command).Run()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:148 +0xa5
  github.com/urfave/cli/v2.(*Command).Run()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:264 +0x128b
  github.com/urfave/cli/v2.(*App).RunContext()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:333 +0x10e4
  kon.nect.sh/specter/integrations.TestTunnel.func3()
      /home/rachel/code/specter/integrations/tunnel_test.go:164 +0x88
  kon.nect.sh/specter/integrations.TestTunnel.func13()
      /home/rachel/code/specter/integrations/tunnel_test.go:168 +0x47

Previous write at 0x000001b75b28 by goroutine 12:
  github.com/urfave/cli/v2.(*Command).setup()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:134 +0x9be
  github.com/urfave/cli/v2.(*Command).Run()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:148 +0xa5
  github.com/urfave/cli/v2.(*Command).Run()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:264 +0x128b
  github.com/urfave/cli/v2.(*App).RunContext()
      /home/rachel/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:333 +0x10e4
  kon.nect.sh/specter/integrations.TestTunnel.func3()
      /home/rachel/code/specter/integrations/tunnel_test.go:164 +0x88
  kon.nect.sh/specter/integrations.TestTunnel.func13()
      /home/rachel/code/specter/integrations/tunnel_test.go:168 +0x47

Goroutine 11 (running) created at:
  kon.nect.sh/specter/integrations.TestTunnel()
      /home/rachel/code/specter/integrations/tunnel_test.go:163 +0x2689
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47

Goroutine 12 (running) created at:
  kon.nect.sh/specter/integrations.TestTunnel()
      /home/rachel/code/specter/integrations/tunnel_test.go:163 +0x2689
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47
==================
```

## Expected behavior

No data race. 

## Additional context

This actually doesn't affect the test results (servers started correctly with the correct parameters). However,
```go
var (
	defaultSliceFlagSeparator = ","
	disableSliceFlagSeparator = false
)
```
in `flag.go` are not protected from concurrent access.

## Want to fix this yourself?

Gonna need some pointers

## Run `go version` and paste its output here

```
go version go1.19.4 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rachel/.cache/go-build"
GOENV="/home/rachel/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rachel/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rachel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/rachel/code/specter/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1222184028=/tmp/go-build -gno-record-gcc-switches"
```

### PR DESCRIPTION
**Pull request by zllovesuki**
## What type of PR is this?

- bug fix

## What this PR does / why we need it:

Remove the dependencies of shared variable from slice type flags parsing, and instead use a `separatorSpec` for parsing. This should not fail downstream dependencies that may be running multiple `*App` concurrently with race detector on.

## Which issue(s) this PR fixes:

Fixes #1670

## Special notes for your reviewer:

This commit creates a new type separatorSpec that will get passed into flag parser, instead of reading from shared variables. I'm uncertain that if I may have missed some parts of the code to be injected. Please let me know if I overlooked anything.

With `HideVersion` and `HideHelp`, the integration test mentioned in the issue is now passing with race detector on with this patch applied.

## Testing

Should be passing with `separatorSpec`, assuming that the call site has the configured `separatorSpec` from caller.

## Release Notes

```release-note
flag: remove dependencies on shared variables when parsing slices
```

### CODE REVIEW

File: app.go [hunk 1]
```diff
@@ -293,11 +298,12 @@ func (a *App) newRootCommand() *Command {
...
 		SkipFlagParsing:        a.SkipFlagParsing,
 		isRoot:                 true,
+		separator:              a.separator,
 	}
 }
 
-func (a *App) newFlagSet() (*flag.FlagSet, error) {
-	return flagSet(a.Name, a.Flags)
+func (a *App) newFlagSet(spec separatorSpec) (*flag.FlagSet, error) {
+	return flagSet(a.Name, a.Flags, spec)
```
Comment (skelouse) [inline app.go:306]: Could just send a.separator here

File: command.go [hunk 2]
```diff
@@ -274,8 +276,8 @@ func (c *Command) Run(cCtx *Context, arguments ...string) (err error) {
 	return err
 }
 
-func (c *Command) newFlagSet() (*flag.FlagSet, error) {
-	return flagSet(c.Name, c.Flags)
+func (c *Command) newFlagSet(spec separatorSpec) (*flag.FlagSet, error) {
+	return flagSet(c.Name, c.Flags, spec)
```
Comment (skelouse) [inline command.go:280]: could use c.separator

File: flag.go [hunk 3]
```diff
@@ -167,10 +167,13 @@ type Countable interface {
 	Count() int
 }
 
-func flagSet(name string, flags []Flag) (*flag.FlagSet, error) {
+func flagSet(name string, flags []Flag, spec separatorSpec) (*flag.FlagSet, error) {
 	set := flag.NewFlagSet(name, flag.ContinueOnError)
 
 	for _, f := range flags {
+		if c, ok := f.(customizedSeparator); ok {
+			c.WithSeparatorSpec(spec)
```
Comment (skelouse) [inline flag.go:175]: Could this be done in apply of slice flags?

Comment (zllovesuki) [reply flag.go:175]: I didn't want to change the signature of `.Apply()`

Comment (skelouse) [reply flag.go:175]: If the flag has separator, flag.Apply() signature does not have to change

Comment (zllovesuki) [reply flag.go:175]: I might've missed the memo somewhere, but how would the `Flag` get the separatorSpec

Comment (skelouse) [reply flag.go:175]: Ahh I see the difficulty there.

File: app.go [hunk 4]
```diff
@@ -216,15 +217,25 @@ func (a *App) Setup() {
 		})
 	}
 
+	if len(a.SliceFlagSeparator) != 0 {
+		a.separator.customized = true
+		a.separator.sep = a.SliceFlagSeparator
+	}
+
+	if a.DisableSliceFlagSeparator {
```
Comment (dearchap) [inline app.go:225]:
```if a.DisableSliceFlagSeparator {

} else if len(a.SliceFlagSeparator) != 0 {

}```

**Review by dearchap — APPROVED** [review]
Minor comments. Thanks for the PR @zllovesuki

**Comment by skelouse** [comment]
> Minor comments. Thanks for the PR @zllovesuki

Any thoughts on failing tests?
