### PR TITLE
Add SliceFlag wrapper and fix bugs in existing implementations

### LINKED ISSUE #1410: IntSliceFlag and friends don't work correctly with destination (+ behavior quirks relating to value)
## My urfave/cli version is

v2.8.1

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

I've noticed a some issues / inconsistencies, while implementing https://github.com/urfave/cli/pull/1409. I'm creating this issue just to make it clear what they are.

- It appears `Destination` fields were added to the `IntSliceFlag`, `Int64SliceFlag`, and `Float64SliceFlag` structs, without actually implementing the necessary behavior
- The `StringSliceFlag.Value` (default value) field may be modified by values passed in by environment variables
- It doesn't seem like a problem, but the `Value` field seems like it should never be modified (e.g. don't initialise it if it's nil / use a local variable instead)

Past issues/PRs that may be relevant: https://github.com/urfave/cli/issues/1235, https://github.com/urfave/cli/pull/981, https://github.com/urfave/cli/pull/1178

Currently open issues that may be relevant: https://github.com/urfave/cli/issues/1224, https://github.com/urfave/cli/issues/1143

## To reproduce

N/A, but take a look at https://github.com/urfave/cli/pull/1409, particularly the existing test I modified (for the second issue)

## Observed behavior

See above

## Expected behavior

The value / destination support of `IntSliceFlag` etc should be equivalent to `StringSliceFlag`. That said, there's a bit of a question around handling the (set) empty string env var case, however. See the note on my PR.

## Run `go version` and paste its output here

```
go version go1.18.2 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/joey/.cache/go-build"
GOENV="/home/joey/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/joey/under/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/joey/under/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/f/dev/urfave-cli/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1554591512=/tmp/go-build -gno-record-gcc-switches"
```

### PR DESCRIPTION
**Pull request by joeycumines**
## What type of PR is this?

- bug
- feature

## What this PR does / why we need it:

The SliceFlag implementation and associated aliases (MultiStringFlag, etc) extend the existing slice implementations (StringSliceFlag, etc) to support actual slices as the flag value and destination.

This change also fixes various bugs in the existing implementation. Notably, the StringSliceFlag.Apply implementation would modify the input (default) Value, if an env var was set, and no destination was provided. The bugs fixed in the other three implementations were all already fixed in either StringSliceFlag, or in one case (ignoring empty env var) in Float64SliceFlag.

## Which issue(s) this PR fixes:

Fixes #1410

## Special notes for your reviewer:

I'm not sure if the "ignoring empty env var" behavior is desirable or not. It seems like it should be made consistent, at least.

## Release Notes

```release-note
Add SliceFlag and aliases (MultiStringFlag, MultiIntFlag, MultiFloat64Flag, MultiInt64Flag).
Fix value/destination behavior for slice flags.
```

### CODE REVIEW

**Comment by joeycumines** [comment]
Thanks @meatballhat :)

I've added a build constraint + restructured it slightly, so it should no longer impact support for older versions of Go.

**Comment by joeycumines** [comment]
Could I get an update on getting this merged?

I don't want to forget I have this PR open, is all :)

Looks like it passes CI now

**Comment by meatballhat** [comment]
@joeycumines Sorry for my delay 😭 This week was 1000% more kiddo chaos than usual for me. Weekend mode: engage 🤘🏼

File: sliceflag.go [hunk 1]
```diff
@@ -0,0 +1,293 @@
...
+	if value, ok := x.value.(Serializer); ok {
+		return value.Serialize()
+	}
+	return x.String()
+}
+
+// applyFlagValueHook wraps calls apply then wraps flags to call a hook function on update and after initial apply.
+func applyFlagValueHook(set *flag.FlagSet, apply func(set *flag.FlagSet) error, hook func()) error {
+	if apply == nil || set == nil || hook == nil {
+		panic(`invalid input`)
```
Comment (meatballhat) [inline sliceflag.go:202]: Given that this is a library and this function already has an `error` return signature, I think I'd rather this not `panic`. WDYT?

**Review by meatballhat — APPROVED** [review]
@joeycumines 🤯 Wow. Very wow.

File: sliceflag.go (hunk 1 above)
Comment (joeycumines) [reply sliceflag.go:202]: IMO, panics are ideal for "misuse of API" cases, especially internal / unexported APIs, as, generally speaking, panics are more likely to be noticed, and you want to notice any such cases. The least-effort alternative is just having it panic once it tries to call a nil function, which is similar, but more likely to go unnoticed.

If there was a use case for having it return an error, that could always be added later.
