### PR TITLE
Fix:(issue_2169) Allow trim space for string slice flags

### LINKED ISSUE #2169: TrimSpace Config has no effect on StringSliceFlag
## My urfave/cli version is

v3.3.8

## Checklist

- [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v3 manual is [here](https://cli.urfave.org/v3/getting-started/)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Describe the bug

Strings arguments to a StringSliceFlag are always trimmed regardless of the `TrimSpace` configuration

## To reproduce

```go
// See flag_test.go

// Existing test
		{
			name:   "StringSliceFlag valid with TrimSpace",
			input:  "foo , bar ",
			output: []string{"foo", "bar"},
			fl:     &StringSliceFlag{Name: "names", Sources: EnvVars("NAMES"), Config: StringConfig{TrimSpace: true}},
		},

// Add a new test with TrimSpace set to false
		{
			name:   "StringSliceFlag valid without TrimSpace",
			input:  "foo , bar ",
			output: []string{"foo ", " bar "},
			fl:     &StringSliceFlag{Name: "names", Sources: EnvVars("NAMES"), Config: StringConfig{TrimSpace: false}},
		},
```

## Observed behavior

Spaces are trimmed regardless:

```go
[]string{"foo", "bar"}
```

## Expected behavior

I expected it to preserve spaces with `TrimSpace` set to false

```go
 []string{"foo ", " bar "}
```

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #2169 

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

Update the string slice test in flag_test to have a case which has trim space off by default. 

## Release Notes

_(REQUIRED)_

```release-note
StringSlice flags now honour the TrimSpace in StringConfig
```

### CODE REVIEW

File: command_test.go [hunk 1]
```diff
@@ -4311,6 +4311,9 @@ func TestCommandReadArgsFromStdIn(t *testing.T) {
 				},
 				&StringSliceFlag{
 					Name: "ssf",
+					Config: StringConfig{
+						TrimSpace: true,
+					},
```
Comment (abitrolly) [inline command_test.go:4316]: Is it possible to make `TrimSpace` a first level option of `StringSliceFlag`?

Comment (ayoisaiah) [reply command_test.go:4316]: @dearchap @abitrolly  Following up on this 🙏

**Comment by dearchap** [comment]
Merging as is for now.
