### PR TITLE
Fix:(issue_1607) Allow exporting command and arguments/options to json

### LINKED ISSUE #1607: `ToJSON` or JSON format for import/export of CLI options
I wonder if it is possible to create a generic options definition serialization/exchange format in JSON?

Then the stuff like Markdown help, man pages and command line completion (https://github.com/urfave/cli/pull/1606/files) could be generated from that JSON format by external tools without bloating the size of `urfave/cli` binaries (https://github.com/urfave/cli/discussions/1594).

I already tried to play with that a bit with Python here - https://github.com/abitrolly/podman-compose/commit/0cd4197a90453dbb299aab8e8b6c3d0191e59d16 - so it is possible to extract that bit to see if `urfave/cli` export and Python `argparse` export can be compatible.

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- feature

## What this PR does / why we need it:

_(REQUIRED)_

Allows us to have a starting point for a framework for exporting cli to JSON. 

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #1607 

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

Added a new test case TestJSONExportCommand which shows that the entire command graph can be exported to JSON. 

## Release Notes

_(REQUIRED)_

```release-note
Once a root command is constructed. json.Marshal can be used to export the command graph to a string of bytes. This can be piped to a template rendering tool such as [tpl](https://github.com/bluebrown/go-template-cli)  along with a template file to render markdown/man pages. 
```

### CODE REVIEW

File: command.go [hunk 1]
```diff
@@ -28,108 +28,109 @@ type contextKey string
...
+	HideHelp bool `json:"hideHelp"`
 	// Ignored if HideHelp is true.
-	HideHelpCommand bool
+	HideHelpCommand bool `json:"hideHelpCommand"`
 	// Boolean to hide built-in version flag and the VERSION section of help
-	HideVersion bool
-	// Boolean to enable shell completion commands
-	EnableShellCompletion bool
+	HideVersion bool `json:"hideVersion"`
+	// Boolean to enable shell completion com.mands
```
Comment (meatballhat) [inline command.go:59]: accidental?

```suggestion
	// Boolean to enable shell completion commands
```

**Review by meatballhat — APPROVED** [review]
