### PR TITLE
Fix: Nested help command has a incorrect HelpName

### LINKED ISSUE #1570: Nested help command has a incorrect HelpName
## My urfave/cli version is

v2.23.4

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

Help command has a help subcommand in default, so you can show help of help like `cmd help help`.
However, since help commands internally refers to the same object, its HelpName is not updated and incorrect value is displayed.

## To reproduce

```go
func main() {
	(&cli.App{
		Name: "a",
		Commands: []*cli.Command{
			{
				Name:        "b",
				Subcommands: []*cli.Command{{Name: "c"}},
			},
		},
	}).Run(os.Args)
}
```

```
$ a b c help help

NAME:
   a b help - Shows a list of commands or help for one command

USAGE:
   a b help [command options] [command]

OPTIONS:
   --help, -h  show help (default: false)
```

## Want to fix this yourself?

In the first place, for me, it's strange to be able to call help of help.
If there're no problems, I'd like to solve by enabling `HideHelp` of help command.
I'd appreciate your opinion.

### PR DESCRIPTION
**Pull request by remiposo**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

- Fixed incorrect HelpName of helpCommand
- Changed HideHelp of helpCommand to avoid nested helpCommand
- Added related tests
  - Fixed `ShowCommandHelp` to pass tests

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #1570

## Special notes for your reviewer:

_(fill-in or delete this section)_

In `ShowCommandHelp`, `len(c.Subcommands) != 0` is used as the condition.. What does it mean? 
Even if a command has no subcommand, I think helpCommand should be added. 
In fact, helpCommand can be invoked although it does not appear in help msg.

I didn't change it this time, because some of the existing test cases asserting entire help msg failed.

## Testing

_(fill-in or delete this section)_

- `Test_helpCommand_HelpName` tests HelpName of helpCommand
- `Test_helpCommand_HideHelpCommand` and `Test_helpCommand_HideHelpFlag` test nested helpCommand call

## Release Notes

_(REQUIRED)_

```release-note

```

### CODE REVIEW

**Review by dearchap — APPROVED** [review]

**Comment by dearchap** [comment]
Thanks for the complete patch @remiposo

File: help.go [hunk 1]
```diff
@@ -246,11 +248,13 @@ func ShowCommandHelp(ctx *Context, command string) error {
...
 		if c.HasName(command) {
-			if !ctx.App.HideHelpCommand && !c.HasName(helpName) && len(c.Subcommands) != 0 && c.Command(helpName) == nil {
-				c.Subcommands = append(c.Subcommands, helpCommandDontUse)
-			}
-			if !ctx.App.HideHelp && HelpFlag != nil {
-				c.appendFlag(HelpFlag)
+			if !c.HideHelp {
+				if !c.HideHelpCommand && len(c.Subcommands) != 0 && c.Command(helpName) == nil {
+					c.Subcommands = append(c.Subcommands, helpCommandDontUse)
+				}
```
Comment (dearchap) [inline help.go:254]: @remiposo can you add a test case for app -h help and app cmd -h help etc ?

**Comment by remiposo** [comment]
@dearchap Thank you for your review.
- Add test cases that you pointed out
- Add test on appending help in `ShowCommandHelp` to increase coverage

File: help.go (hunk 1 above)
Comment (remiposo) [reply help.go:254]: Sure

**Review by dearchap — APPROVED** [review]
