### PR TITLE
Fix:(issue_1962) Fix tests failing on 32 bit architectures

### LINKED ISSUE #1962: TestYamlFileUint fails on 32 bit architectures
I'm working on packaging this library for Debian, and after enabling the altsrc package, I noticed that the test cases below fail on 32 bit architectures:

https://github.com/urfave/cli/blob/a4832fd31def973ae9fb5aedba571db952463ceb/altsrc/yaml_file_loader_test.go#L293-L302

This apples on each if `i386`, `armhf` and `armel`:

```
119s     yaml_file_loader_test.go:261: 4 testcast: expect error but Mismatched type for flag 'test'. Expected 'uint' but actual is 'int64'
119s     yaml_file_loader_test.go:261: 5 testcast: expect error but Mismatched type for flag 'test'. Expected 'uint' but actual is 'uint64'
119s --- FAIL: TestYamlFileUint (0.00s)
```

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #1962 

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

GOARCH=386 go test ./altsrc/

## Release Notes

_(REQUIRED)_

```release-note
Fix overflow in tests on 32 bit architectures
```

### CODE REVIEW

File: altsrc/yaml_file_loader_test.go [hunk 1]
```diff
@@ -228,12 +227,12 @@ func TestYamlFileUint(t *testing.T) {
...
 		{
 			"test",
-			"test: 9223372036854775807", //int
+			"test: 775807", //int
 			false,
 		},
 		{
 			"test",
-			"test: 9223372036854775808", //uintt64
+			"test: 4775808", //uintt64
```
Comment (bartekpacia) [inline altsrc/yaml_file_loader_test.go:235]: `uintt64` -> `uint64`?

**Review by bartekpacia — APPROVED** [review]

File: altsrc/yaml_file_loader_test.go (hunk 1 above)
Comment (dearchap) [reply altsrc/yaml_file_loader_test.go]: Updated
