### PR TITLE
Fix:(issue_1505) Fix flag alignment in help

### LINKED ISSUE #1505: Subcommand help does not have a newline for flags
## My urfave/cli version is

2.17.1

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [ ] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [ ] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is automatically downloading the latest version.

## Describe the bug

When there is a subcommand and you type in `help`, the usage text for flags are not separated by a newline. For example,

```
go run cmd/main.go remove --help
```

Will display

```
NAME:
   main remove - remove subcommand

USAGE:
   main remove [command options] [arguments...]

OPTIONS:
   --flag1 value  flag1 usage text--flag112 value  flag112 usage text
```

## To reproduce

This is my source code

```go
package cli

import (
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func Cli() {
	flags := []cli.Flag{
		&cli.StringFlag{
			Name:  "flag1",
			Usage: "flag1 usage text",
		},
		&cli.PathFlag{
			Name:  "flag112",
			Usage: "flag112 usage text",
		},
	}

	app := &cli.App{
		Commands: []*cli.Command{
			{
				Name:  "remove",
				Usage: "remove subcommand",
				Flags: flags,
				Action: func(cCtx *cli.Context) error {
					return nil
				},
			},
		},
	}

	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```

## Observed behavior

This is the output.

```
NAME:
   main remove - remove subcommand

USAGE:
   main remove [command options] [arguments...]

OPTIONS:
   --flag1 value  flag1 usage text--flag112 value  flag112 usage text
```

## Expected behavior

With newline and indent for subcommand flags.

```
NAME:
   main remove - remove subcommand

USAGE:
   main remove [command options] [arguments...]

OPTIONS:
   --flag1   value  flag1 usage text
   --flag112 value  flag112 usage text
```

## Additional context

N/A

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for
this bug is easily explained and very small, free free to create a
pull request for it.

## Run `go version` and paste its output here

```
go version go1.19.1 darwin/arm64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/tn6091/Library/Caches/go-build"
GOENV="/Users/tn6091/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tn6091/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tn6091/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bf/3p7t8_1j5yv6vl9zprhl2lfr0000gq/T/go-build2640204268=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #1505 
## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

## Release Notes

Use the user provide example
_(REQUIRED)_

```release-note

```

### CODE REVIEW

**Review by icholy — DISMISSED** [review]

**Comment by dearchap** [comment]
@icholy Help is very very fragile so to keep everything consistent I componentized the templates

File: template.go [hunk 1]
```diff
@@ -13,73 +39,56 @@ VERSION:
    {{.Version}}{{end}}{{end}}{{if .Description}}
 
 DESCRIPTION:
-   {{wrap .Description 3}}{{end}}{{if len .Authors}}
+   {{template "descriptionTemplate" .}}{{end}}{{if len .Authors}}
```
Comment (abitrolly) [inline template.go:42]: It is possible to strip whitespace between tags https://pkg.go.dev/text/template#hdr-Text_and_spaces
```suggestion
   {{template "descriptionTemplate" .}}{{end}}
{{- if len .Authors}}
```

File: help_test.go [hunk 2]
```diff
@@ -1360,7 +1360,7 @@ DESCRIPTION:
 
 OPTIONS:
    --help, -h  show help (default: false)
-`
+   `
```
Comment (julian7) [inline help_test.go:1363]: Can we get rid of the three spaces a the last line?

**Review by julian7 — DISMISSED** [review]

File: help_test.go (hunk 2 above)
Comment (dearchap) [reply help_test.go:1370]: Yes. One step at a time.

Comment (dearchap) [reply help_test.go]: Okay fixed. Please look at the template changes.
