### PR TITLE
style: fix typos

### LINKED ISSUE #1995: Fix typo
I checked typo using https://github.com/crate-ci/typos , then a lot of typo are found.

```console
$ git rev-parse HEAD
c4cd0a51cc113a90eca318cc8f7d328f05a5f2b7

$ typos --version
typos-cli 1.26.8
```

```console
~/repos/src/github.com/urfave/cli main
$ typos
error: `halp` should be `help`
  --> ./docs/v3/examples/generated-help-text.md:80:22
   |
80 |   "args": ["&#45;&#45halp"],
   |                      ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v3/examples/generated-help-text.md:81:24
   |
81 |   "output": "haaaaalp.*HALP"
   |                        ^^^^
   |
error: `halp` should be `help`
  --> ./docs/v3/examples/generated-help-text.md:96:22
   |
96 |   Aliases: []string{"halp"},
   |                      ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v3/examples/generated-help-text.md:97:13
   |
97 |   Usage:   "HALP",
   |             ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v3/examples/generated-help-text.md:98:30
   |
98 |   Sources: cli.EnvVars("SHOW_HALP", "HALPPLZ"),
   |                              ^^^^
   |
error: `halp` should be `help`
  --> ./docs/v3/examples/full-api-example.md:34:38
   |
34 |  cli.HelpFlag = &cli.BoolFlag{Name: "halp"}
   |                                      ^^^^
   |
error: `Thar` should be `Than`, `That`
  --> ./docs/v3/examples/full-api-example.md:165:36
    |
165 |    fmt.Fprintf(cmd.Root().Writer, "Thar be no %q here.\n", command)
    |                                    ^^^^
    |
error: `som` should be `some`
  --> ./docs/v3/examples/combining-short-options.md:20:27
   |
20 |   "args": ["short", "&#45;som", "Some message"],
   |                           ^^^
   |
error: `som` should be `some`
  --> ./docs/v3/examples/combining-short-options.md:69:8
   |
69 | $ cmd -som "Some message"
   |        ^^^
   |
error: `ba` should be `by`, `be`
  --> ./suggestions_test.go:26:11
   |
26 |   {"aa", "ba", 0.6666666666666666},
   |           ^^
   |
error: `ba` should be `by`, `be`
  --> ./suggestions_test.go:27:5
   |
27 |   {"ba", "aa", 0.6666666666666666},
   |     ^^
   |
error: `hel` should be `help`, `hell`, `heal`
  --> ./suggestions_test.go:77:9
   |
77 |   {"", "hel", "--help"},
   |         ^^^
   |
error: `halp` should be `help`
  --> ./docs/v2/examples/generated-help-text.md:79:22
   |
79 |   "args": ["&#45;&#45halp"],
   |                      ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v2/examples/generated-help-text.md:80:24
   |
80 |   "output": "haaaaalp.*HALP"
   |                        ^^^^
   |
error: `halp` should be `help`
  --> ./docs/v2/examples/generated-help-text.md:94:22
   |
94 |   Aliases: []string{"halp"},
   |                      ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v2/examples/generated-help-text.md:95:13
   |
95 |   Usage:   "HALP",
   |             ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v2/examples/generated-help-text.md:96:27
   |
96 |   EnvVars: []string{"SHOW_HALP", "HALPPLZ"},
   |                           ^^^^
   |
error: `halp` should be `help`
  --> ./docs/v2/examples/full-api-example.md:34:38
   |
34 |  cli.HelpFlag = &cli.BoolFlag{Name: "halp"}
   |                                      ^^^^
   |
error: `Thar` should be `Than`, `That`
  --> ./docs/v2/examples/full-api-example.md:172:34
    |
172 |    fmt.Fprintf(cCtx.App.Writer, "Thar be no %q here.\n", command)
    |                                  ^^^^
    |
error: `ser` should be `set`
  --> ./flag_test.go:2190:2
     |
2190 |  ser0 := sl0.Serialize()
     |  ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2192:32
     |
2192 |  require.GreaterOrEqual(t, len(ser0), len(slPfx), "serialized shorter than expected")
     |                                ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2195:14
     |
2195 |  _ = sl1.Set(ser0)
     |              ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2202:2
     |
2202 |  ser0 := sl0.Serialize()
     |  ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2204:32
     |
2204 |  require.GreaterOrEqual(t, len(ser0), len(slPfx), "serialized shorter than expected")
     |                                ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2207:14
     |
2207 |  _ = sl1.Set(ser0)
     |              ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2214:2
     |
2214 |  ser0 := sl0.Serialize()
     |  ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2216:32
     |
2216 |  require.GreaterOrEqual(t, len(ser0), len(slPfx), "serialized shorter than expected")
     |                                ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2219:14
     |
2219 |  _ = sl1.Set(ser0)
     |              ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2226:2
     |
2226 |  ser0 := sl0.Serialize()
     |  ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2228:32
     |
2228 |  require.GreaterOrEqual(t, len(ser0), len(slPfx), "serialized shorter than expected")
     |                                ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2231:14
     |
2231 |  _ = sl1.Set(ser0)
     |              ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2238:2
     |
2238 |  ser0 := m0.Serialize()
     |  ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2240:32
     |
2240 |  require.GreaterOrEqual(t, len(ser0), len(slPfx), "serialized shorter than expected")
     |                                ^^^
     |
error: `ser` should be `set`
  --> ./flag_test.go:2243:13
     |
2243 |  _ = m1.Set(ser0)
     |             ^^^
     |
error: `som` should be `some`
  --> ./docs/v2/examples/combining-short-options.md:20:27
   |
20 |   "args": ["short", "&#45;som", "Some message"],
   |                           ^^^
   |
error: `som` should be `some`
  --> ./docs/v2/examples/combining-short-options.md:68:8
   |
68 | $ cmd -som "Some message"
   |        ^^^
   |
error: `unmarshaling` should be `unmarshalling`
  --> ./docs/CHANGELOG.md:74:32
   |
74 | - Added `Float64SliceFlag` for unmarshaling a list of floats from the user
   |                                ^^^^^^^^^^^^
   |
error: `ist` should be `is`, `it`, `its`, `sit`, `list`
  --> ./docs/v1/examples/flags.md:441:23
    |
441 |     fmt.Println("yaml ist rad")
    |                       ^^^
    |
error: `halp` should be `help`
  --> ./docs/v1/examples/generated-help-text.md:81:22
   |
81 |   "args": ["&#45;&#45halp"],
   |                      ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v1/examples/generated-help-text.md:82:24
   |
82 |   "output": "haaaaalp.*HALP"
   |                        ^^^^
   |
error: `halp` should be `help`
  --> ./docs/v1/examples/generated-help-text.md:96:12
   |
96 |     Name: "halp, haaaaalp",
   |            ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v1/examples/generated-help-text.md:97:13
   |
97 |     Usage: "HALP",
   |             ^^^^
   |
error: `HALP` should be `HELP`
  --> ./docs/v1/examples/generated-help-text.md:98:19
   |
98 |     EnvVar: "SHOW_HALP,HALPPLZ",
   |                   ^^^^
   |
error: `som` should be `some`
  --> ./docs/v1/examples/combining-short-options.md:18:27
   |
18 |   "args": ["short", "&#45;som", "Some message"],
   |                           ^^^
   |
error: `som` should be `some`
  --> ./docs/v1/examples/combining-short-options.md:66:8
   |
66 | $ cmd -som "Some message"
   |        ^^^
   |
error: `halp` should be `help`
  --> ./docs/v1/examples/version-flag.md:109:38
    |
109 |   cli.HelpFlag = cli.BoolFlag{Name: "halp"}
    |                                      ^^^^
    |
error: `pn` should be `on`
  --> ./flag.go:356:2
    |
356 |  pn := prefixedNames(f.Names(), placeholder)
    |  ^^
    |
error: `pn` should be `on`
  --> ./flag.go:359:3
    |
359 |   pn = pn + " [ " + pn + " ]"
    |   ^^
    |
error: `pn` should be `on`
  --> ./flag.go:359:8
    |
359 |   pn = pn + " [ " + pn + " ]"
    |        ^^
    |
error: `pn` should be `on`
  --> ./flag.go:359:21
    |
359 |   pn = pn + " [ " + pn + " ]"
    |                     ^^
    |
error: `pn` should be `on`
  --> ./flag.go:362:60
    |
362 |  return withEnvHint(df.GetEnvVars(), fmt.Sprintf("%s\t%s", pn, usageWithDefault))
    |                                                            ^^
    |
error: `Thar` should be `Than`, `That`
  --> ./docs/v1/examples/version-flag.md:249:32
    |
249 |     fmt.Fprintf(c.App.Writer, "Thar be no %q here.\n", command)
    |                                ^^^^
    |
error: `trigerred` should be `triggered`
  --> ./command_test.go:3056:66
     |
3056 |  assert.True(t, cmd1 == 1 && cmd2 == 0, "Expected command1 to be trigerred once")
     |                                                                  ^^^^^^^^^
     |
error: `trigerred` should be `triggered`
  --> ./command_test.go:3063:66
     |
3063 |  assert.True(t, cmd1 == 1 && cmd2 == 0, "Expected command1 to be trigerred once")
     |                                                                  ^^^^^^^^^
     |
error: `trigerred` should be `triggered`
  --> ./command_test.go:3070:66
     |
3070 |  assert.True(t, cmd1 == 1 && cmd2 == 0, "Expected command1 to be trigerred once")
     |                                                                  ^^^^^^^^^
     |
error: `trigerred` should be `triggered`
  --> ./command_test.go:3077:66
     |
3077 |  assert.True(t, cmd1 == 0 && cmd2 == 1, "Expected command1 to be trigerred once")
     |                                                                  ^^^^^^^^^
     |
error: `trigerred` should be `triggered`
  --> ./command_test.go:3084:66
     |
3084 |  assert.True(t, cmd1 == 0 && cmd2 == 1, "Expected command1 to be trigerred once")
     |                                                                  ^^^^^^^^^
     |
```

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
## What type of PR is this?

_(REQUIRED)_

- documentation

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #1995

## Special notes for your reviewer:

_(fill-in or delete this section)_

I'm using typos to detect and fix typo.

https://github.com/crate-ci/typos

typos supports auto fix, but it doesn't fix all typo and may have false positive.
We need to check if the fix is correct.
And we may need to configure typos.

## Testing

_(fill-in or delete this section)_

## Release Notes

_(REQUIRED)_

```release-note

```

### CODE REVIEW

File: flag_test.go [hunk 1]
```diff
@@ -2187,60 +2187,60 @@ func (p *Parser) Get() interface{} {
 
 func TestStringSlice_Serialized_Set(t *testing.T) {
 	sl0 := NewStringSlice("a", "b")
-	ser0 := sl0.Serialize()
+	set0 := sl0.Serialize()
```
Comment (suzuki-shunsuke) [inline flag_test.go:2190]: I guess this is incorrect.

File: flag.go [hunk 2]
```diff
@@ -353,13 +353,13 @@ func stringifyFlag(f Flag) string {
 
 	usageWithDefault := strings.TrimSpace(usage + defaultValueString)
 
-	pn := prefixedNames(f.Names(), placeholder)
+	on := prefixedNames(f.Names(), placeholder)
```
Comment (suzuki-shunsuke) [inline flag.go:356]: I guess this is incorrect.
Maybe we should exclude *.go.

**Comment by suzuki-shunsuke** [comment]
I excluded *.go.

```sh
typos -w --exclude '**/*.go'
```

**Comment by suzuki-shunsuke** [comment]
test-docs failed.

https://github.com/urfave/cli/actions/runs/11535764321/job/32111183783?pr=1996

```
time="2024-10-26T23:31:54Z" level=info msg=done error_count=1 example_count=31 fields.time=8.317808798s source_count=16
time="2024-10-26T23:31:54Z" level=error msg="expected output does not match actual: \"serve: true\\noption: true\\nmessage: Some message\\n\" != \"\""
exit status 2
```

**Comment by suzuki-shunsuke** [comment]
📝 `make ensure-gfmrun` doesn't work on Apple Silicon (darwin/arm64) because the pre-built binary of gfmrun for darwin/arm64 is missing.  

https://github.com/urfave/cli/blob/94107c2a95f090ffafe6e2ec7c9fb7355864f88e/scripts/build.go#L550-L555
https://github.com/urfave/gfmrun/releases

We need to build gfmrun for darwin/arm64 or use the asset for darwin/amd64.

**Comment by suzuki-shunsuke** [comment]
😁 You can now install gfmrun using [aqua](https://aquaproj.github.io/), which is a modern CLI version manager.

- https://github.com/aquaproj/aqua-registry/pull/28180
- https://github.com/aquaproj/aqua-registry/releases/tag/v4.242.0

**Comment by suzuki-shunsuke** [comment]
I could reproduce the issue.

```console
$ gfmrun --sources docs/v3/examples/combining-short-options.md
INFO[0000] loading                                       languages=/Users/shunsukesuzuki/.cache/gfmrun/languages.yml
INFO[0000] start                                         i=1/1 lang=go line=23 source=docs/v3/examples/combining-short-options.md
go: creating new go.mod: module gfmrun/example23
go: to add module requirements and sums:
	go mod tidy
go: finding module for package github.com/urfave/cli/v3
go: found github.com/urfave/cli/v3 in github.com/urfave/cli/v3 v3.0.0-alpha9.1
INFO[0002] finish                                        fields.time=2.041508375s i=1/1 lang=go line=23 source=docs/v3/examples/combining-short-options.md
INFO[0002] checked                                       fields.time=2.04220175s source=docs/v3/examples/combining-short-options.md
INFO[0002] done                                          error_count=1 example_count=1 fields.time=2.04255s source_count=1
ERRO[0002] expected output does not match actual: "serve: true\noption: true\nmessage: Some message\n" != ""
```

File: docs/v1/examples/combining-short-options.md [hunk 3]
```diff
@@ -63,7 +63,7 @@ and `-m` respectively, setting `UseShortOptionHandling` will also support the
 following syntax:
 
 ```
-$ cmd -som "Some message"
+$ cmd -some "Some message"
```
Comment (suzuki-shunsuke) [inline docs/v1/examples/combining-short-options.md:66]: Oh, I see. `som` isn't typo.

File: docs/v1/examples/generated-help-text.md [hunk 4]
```diff
@@ -93,9 +93,9 @@ import (
 
 func main() {
   cli.HelpFlag = cli.BoolFlag{
-    Name: "halp, haaaaalp",
```
Comment (suzuki-shunsuke) [inline docs/v1/examples/generated-help-text.md:96]: Ah, this isn't typo in this context.

**Comment by suzuki-shunsuke** [comment]
📝

```console
$ typos
error: `Thar` should be `Than`, `That`
  --> ./docs/v3/examples/full-api-example.md:165:36
    |
165 |    fmt.Fprintf(cmd.Root().Writer, "Thar be no %q here.\n", command)
    |                                    ^^^^
    |
error: `ba` should be `by`, `be`
  --> ./suggestions_test.go:26:11
   |
26 |   {"aa", "ba", 0.6666666666666666},
   |           ^^
   |
error: `ba` should be `by`, `be`
  --> ./suggestions_test.go:27:5
   |
27 |   {"ba", "aa", 0.6666666666666666},
   |     ^^
   |
error: `hel` should be `help`, `hell`, `heal`
  --> ./suggestions_test.go:77:9
   |
77 |   {"", "hel", "--help"},
   |         ^^^
   |
error: `Thar` should be `Than`, `That`
  --> ./docs/v2/examples/full-api-example.md:174:34
    |
174 |    fmt.Fprintf(cCtx.App.Writer, "Thar be no %q here.\n", command)
    |                                  ^^^^
    |
error: `ist` should be `is`, `it`, `its`, `sit`, `list`
  --> ./docs/v1/examples/flags.md:441:23
    |
441 |     fmt.Println("yaml ist rad")
    |                       ^^^
    |
error: `Thar` should be `Than`, `That`
  --> ./docs/v1/examples/version-flag.md:249:32
    |
249 |     fmt.Fprintf(c.App.Writer, "Thar be no %q here.\n", command)
    |                                ^^^^
    |
```

File: _typos.toml
Comment (Juneezee) [inline _typos.toml:1]: Since we are adding this file, should we also consider adding `crate-ci/typos` into our CI? https://github.com/crate-ci/typos/blob/master/docs/github-action.md

Comment (abitrolly) [reply _typos.toml:1]: I would prefer a Go based tool that doesn't requires additional files.

Or the spellcheck that is completely configured from GitHub Action.

Comment (suzuki-shunsuke) [reply _typos.toml:1]: > Since we are adding this file, should we also consider adding crate-ci/typos into our CI?

Yeah, I agree. Or if we don't want to add this file, I'll simply remove it.

> I would prefer a Go based tool that doesn't requires additional files.

For instance?

> Or the spellcheck that is completely configured from GitHub Action.

This one?

https://github.com/marketplace/actions/github-spellcheck-action

I prefer a tool we can run both local and CI.
I like typos as it is built with Go and support auto fix.
But if there are better tools than typos, it should be fine.

Comment (abitrolly) [reply _typos.toml:1]: > For instance?

I've seen big projects use https://vale.sh but for it somebody needs to build and write the docs https://github.com/urfave/cli/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fdocumentation

> I prefer a tool we can run both local and CI.

`cli` is a library. It does make sense if somebody runs code spellcheck once in a while, but for me spellchecking belongs to editor and CI, and not to the root files of a library project.

>  I like typos as it is built with Go and support auto fix.

No, it is a Rust project https://github.com/crate-ci/typos

File: docs/CHANGELOG.md [hunk 5]
```diff
@@ -71,7 +71,7 @@ The V2 changes were all shipped in [urfave/cli/pull/892](https://github.com/urfa
 ### Added
 
 - Added `NewStringSlice` and `NewIntSlice` for creating their related types
-- Added `Float64SliceFlag` for unmarshaling a list of floats from the user
+- Added `Float64SliceFlag` for unmarshalling a list of floats from the user
```
Comment (bartekpacia) [inline docs/CHANGELOG.md:74]: This is correct (per U.S. English –which I suppose is used everywhere in software world)

File: _typos.toml
Comment (suzuki-shunsuke) [reply _typos.toml:1]: > No, it is a Rust project

Oh, sorry. I was wrong. 😅

Anyway, I don't think we should introduce typos now.
I'll remove _typos.toml.
Thank you for your review.

File: docs/CHANGELOG.md (hunk 5 above)
Comment (suzuki-shunsuke) [reply docs/CHANGELOG.md]: Thank you for your review.
I reverted the fix. 659122249f346ec544384ec23fe0c71f19d0fb10

**Review by Juneezee — APPROVED** [review]
:+1: Thanks for your PR

**Review by abitrolly — APPROVED** [review]
