### PR TITLE
Fix:(issue_1263) FlagNames should return names set via env as well

### LINKED ISSUE #1263: Flag names missing in cli.Context.FlagNames() if set via env. variables
## my urfave/cli version is

**v2.3.0**

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [ ] My project is using go modules.
- [ ] My project is using vendoring.
- [x] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

Flag names missing in `cli.Context.FlagNames()` if set via env. variables.

## To reproduce

```go
package main

import (
	"fmt"
	"github.com/urfave/cli/v2"
	"log"
	"os"
)

func main() {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "testvar",
				EnvVars: []string{"TESTVAR"},
			},
		}, Action: func(c *cli.Context) error {
			fmt.Println("FlagNames()\t", c.FlagNames())
			fmt.Println("testvar\t\t", c.String("testvar"))
			return nil
		},
	}

	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}
```

## Observed behavior

```bash
$ ./main --testvar testval
FlagNames()	 [testvar]
testvar		 testval
$ TESTVAR=testval ./main 
FlagNames()	 []
testvar		 testval
```

## Expected behavior

I expect `cli.Context.FlagNames()` to return flag names irrespectively of which way they were set.

## Run `go version` and paste its output here

```
$ go version
go version go1.16.2 linux/amd64
```

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #1263 
## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

make test 
## Release Notes

_(REQUIRED)_

```release-note

```

### CODE REVIEW

File: context.go [hunk 1]
```diff
@@ -82,15 +82,35 @@ func (cCtx *Context) IsSet(name string) bool {
...
+	m := map[string]struct{}{}
+	var unames []string
+	for _, name := range names {
+		if _, ok := m[name]; !ok {
+			m[name] = struct{}{}
+			unames = append(unames, name)
+		}
+	}
+
+	return unames
```
Comment (meatballhat) [inline context.go:105]: To ensure (more?) consistent behavior

```suggestion
	sort.Strings(unames)

	return unames
```

File: context.go [hunk 2]
```diff
@@ -82,15 +82,35 @@ func (cCtx *Context) IsSet(name string) bool {
...
 
 // FlagNames returns a slice of flag names used by the this context and all of
 // its parent contexts.
 func (cCtx *Context) FlagNames() []string {
 	var names []string
 	for _, pCtx := range cCtx.Lineage() {
-		pCtx.flagSet.Visit(makeFlagNameVisitor(&names))
+		names = append(names, pCtx.LocalFlagNames()...)
 	}
 	return names
```
Comment (meatballhat) [inline context.go:115]: Add `sort.Strings` here, too?

**Review by meatballhat — APPROVED** [review]
