### PR TITLE
fix #1121(StringSliceFlag set default value into destination)

### LINKED ISSUE #1121: v2 bug: ( StringSliceFlag, Value(default) does not set value in Destination )
## my urfave/cli version is

_**github.com/urfave/cli/v2 v2.2.0**_

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

Default value does not setting in destination.

## To reproduce
```
package main

import (
	"github.com/urfave/cli/v2"
	"log"
	"os"
)

type config struct {
	Countries cli.StringSlice
}

func main() {
	cfg := new(config)

	app := cli.NewApp()
	app.Flags = []cli.Flag{
		&cli.StringSliceFlag{
			Name:        "country",
			Aliases:     []string{"c"},
			Value:       cli.NewStringSlice("CA", "US"),
			Destination: &cfg.Countries,
		},
	}
	app.Action = func(c *cli.Context) error {
		log.Printf("%+v", cfg)
		return nil
	}
	_ = app.Run(os.Args)
}
```

## Observed behavior
```
go run main.go 
2020/04/28 22:54:56 &{Countries:{slice:[] hasBeenSet:false}}
```
## Expected behavior
```
go run main.go 
2020/04/28 22:54:56 &{Countries:{slice:[CA US] hasBeenSet:false}}
```
## Additional context
```
go run main.go -c UA
2020/04/28 22:55:00 &{Countries:{slice:[UA] hasBeenSet:true}}
```
## Want to fix this yourself?

set default values manually
`cfg := &config{Countries: []string{"CA", "US"}}`

```
# paste `go version` output in here
```
`go version go1.14.2 darwin/amd64`

## Run `go env` and paste its output here

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/cli_test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n5/7nnknbgd727_w4s8yv3z9hyh0000gn/T/go-build026345303=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### PR DESCRIPTION
**Pull request by sgoroshko**
## What type of PR is this?

_(REQUIRED)_

- [x] bug
- [ ] cleanup  
- [ ] documentation
- [ ] feature

## What this PR does / why we need it:

default value does not set in Destination field in StringSliceFlag.

## Which issue(s) this PR fixes:

https://github.com/urfave/cli/issues/1121

## Release Notes

_(REQUIRED)_

```release-note
 - fix bug, default value does not set in Destination field in StringSliceFlag.
```

### CODE REVIEW

**Comment by lynncyrin** [comment]
This definitely looks like a duplicate of https://github.com/urfave/cli/pull/1123

@sgoroshko & @atif-konasl can you both have a conversation about whose solution you think should move forward? We can't merge both

**Comment by atif-konasl** [comment]
@lynncyrin & @sgoroshko ,
i deleted my PR.

**Comment by lynncyrin** [comment]
ping @urfave/cli for a review here! 👋

File: flag_string_slice.go [hunk 1]
```diff
@@ -116,6 +116,14 @@ func (f *StringSliceFlag) GetValue() string {
 
 // Apply populates the flag given the flag set and environment
 func (f *StringSliceFlag) Apply(set *flag.FlagSet) error {
+
+	if f.Destination != nil {
```
Comment (rliebz) [inline flag_string_slice.go:120]: Nit: These nested `if` statements can be collapsed

```go
if f.Destination != nil && f.Value != nil {
```

**Comment by sgoroshko** [comment]
> Thanks for pulling this fix together.
> 
> One main question here—Is this not a problem for other slice flags as well (int, int64, float)? While it's important we get fixes like this in, it's also necessary that we have consistent behavior between the flag types.

Float64SliceFlag - have no destination field
Int64SliceFlag - have no destination field
IntSliceFlag - have no destination field

**Comment by rliebz** [comment]
Weird that they don't have a destination field, but definitely not a requirement for this change to fix that.

File: flag_string_slice.go (hunk 1 above)
Comment (rliebz) [reply flag_string_slice.go:120]: Bump.

**Comment by sgoroshko** [comment]
fix nested conditions

**Comment by lynncyrin** [comment]
🚢
