### PR TITLE
Fix:(issue_1277) Remove default text for version/help flags

### LINKED ISSUE #1277: can I remove default text when a flag's value is set

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- bug
- documentation
- feature

## What this PR does / why we need it:

_(REQUIRED)_

Remove default text for help/version flags

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #1277 

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

make test

## Release Notes

_(REQUIRED)_

```release-note

```

### CODE REVIEW

File: flag.go [hunk 1]
```diff
@@ -337,8 +339,13 @@ func stringifyFlag(f Flag) string {
 
 	defaultValueString := ""
 
-	if s := df.GetDefaultText(); s != "" {
-		defaultValueString = fmt.Sprintf(formatDefault("%s"), s)
+	// set default text for all flags except bool flags
+	// for bool flags text is set only is DisableDefaultText is not
```
Comment (lorensr) [inline flag.go:343]:
```suggestion
	// for bool flags text is set only if DisableDefaultText is not
```

**Review by lorensr — APPROVED** [review]
Could potentially be useful if it worked on non-book fields? But not for my use case

File: flag.go (hunk 1 above)
Comment (dearchap) [reply flag.go]: Fixed.

**Comment by dearchap** [comment]
> Could potentially be useful if it worked on non-book fields? But not for my use case

Yes it could but for now I think this is good. With other flags it becomes more involved/non-intuitive so I'm going to punt for now.

**Comment by lorensr** [comment]
Sounds good!

**Review by meatballhat — APPROVED** [review]
