### PR TITLE
Fix help results inconsistency

### LINKED ISSUE #557: Confusing "Help" Results
This issue may be related to #163.

Here is the source code (`bug.go`, also available at [<kbd>The Go Playground</kbd>](https://play.golang.org/p/H80jY3BWX4)) for the bug report:

```go
package main

import (
	"os"

	"gopkg.in/urfave/cli.v1"
)

func dummyAction(_ *cli.Context) error {
	return nil
}

var (
	command1 = cli.Command{
		Name:        "command1",
		Usage:       "command1.Usage",
		Description: "command1.Description",
		Subcommands: []cli.Command{
			{
				Action:      dummyAction,
				Name:        "action1",
				Usage:       "command1action1.Usage",
				ArgsUsage:   "<arg1>",
				Description: "command1action1.Description",
			},
			{
				Action:      dummyAction,
				Name:        "action2",
				Usage:       "command1action2.Usage",
				ArgsUsage:   "<arg1> [<arg2>]",
				Description: "command1action2.Description",
			},
			{
				Action:      dummyAction,
				Name:        "action3",
				Usage:       "command1action3.Usage",
				ArgsUsage:   "<arg1> [<arg2>]...",
				Description: "command1action3.Description",
			},
		},
	}
	command2 = cli.Command{
		Action:      dummyAction,
		Name:        "command2",
		Usage:       "command2.Usage",
		Description: "command2.Description",
		Subcommands: []cli.Command{
			{
				Action:      dummyAction,
				Name:        "action1",
				Usage:       "command2action1.Usage",
				ArgsUsage:   "<arg1>",
				Description: "command2action1.Description",
			},
			{
				Action:      dummyAction,
				Name:        "action2",
				Usage:       "command2action2.Usage",
				ArgsUsage:   "<arg1> [<arg2>]",
				Description: "command2action2.Description",
			},
			{
				Action:      dummyAction,
				Name:        "action3",
				Usage:       "command2action3.Usage",
				ArgsUsage:   "<arg1> [<arg2>]...",
				Description: "command2action3.Description",
			},
		},
	}
	command3 = cli.Command{
		Action:      dummyAction,
		Name:        "command3",
		Usage:       "command3.Usage",
		ArgsUsage:   "<arg1> [<arg2>]...",
		Description: "command3.Description",
	}
)

func main() {
	app := cli.NewApp()
	app.Name = "app.Name"
	app.Usage = "app.Usage"
	app.Version = "app.Version"
	app.Commands = []cli.Command{
		command1,
		command2,
		command3,
	}
	app.Run(os.Args)
}
```

When I run `go run bug.go`, `go run bug.go help`, or `go run bug.go --help`, the result is:
```
NAME:
   app.Name - app.Usage

USAGE:
   bug [global options] command [command options] [arguments...]
   
VERSION:
   app.Version
   
COMMANDS:
     command1  command1.Usage
     command2  command2.Usage
     command3  command3.Usage
     help, h   Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

This is fine - the behavior is expected, and the result is consistent.

However, when I run `go run bug.go help command1`, the result is:
```
NAME:
   bug command1 - command1.Usage

USAGE:
   bug command1 [arguments...]

DESCRIPTION:
   command1.Description
```

When I run `go run bug.go command1 --help`, the result is:
```
NAME:
   app.Name command1 - command1.Description

USAGE:
   app.Name command1 command [command options] [arguments...]

COMMANDS:
     action1  command1action1.Usage
     action2  command1action2.Usage
     action3  command1action3.Usage

OPTIONS:
   --help, -h  show help
```

When I run `go run bug.go command1 help`, the result is:
```
NAME:
   app.Name command1 - command1.Description

USAGE:
   app.Name command1 [global options] command [command options] [arguments...]
   
VERSION:
   app.Version
   
COMMANDS:
     action1  command1action1.Usage
     action2  command1action2.Usage
     action3  command1action3.Usage

GLOBAL OPTIONS:
   --help, -h  show help
```

This is very confusing. You can see that in the `NAME` section, sometimes `bug` is printed, and sometimes `app.Name` is printed. Besides, sometimes `command1.Usage` is printed, and sometimes `command1.Description` is printed. You can also find other discrepancies.

I understand that you target to provide a `git` like command library, but at least (`git help` and `git --help`) and (`git help commit` and `git commit --help`) give consistent results.

I also evaluated other commands that comes with sub-commands: `openssl`, `port` (MacPorts), `lvm` (Logical Volume Manager on Linux), `parted`, `apt-get`, `npm` (Node.js Package Manager), `lvm` and `npm` behaved very well, while other commands failed fast by, for example, disabling `command subcommand --help`.

Here is another subcommand library I am evaluating:
https://github.com/google/subcommands
It is not as full featured as `urfave/cli`, so I hope that you could fix the issue so that we can keep using it. Thanks!

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #557 
## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

go test ./...

## Release Notes

_(REQUIRED)_

```release-note

```

### CODE REVIEW

File: help.go [hunk 1]
```diff
@@ -212,9 +238,19 @@ func ShowCommandHelp(ctx *Context, command string) error {
 
 	for _, c := range ctx.App.Commands {
 		if c.HasName(command) {
+			if !ctx.App.HideHelpCommand && !c.HasName(helpName) && len(c.Subcommands) != 0 {
+				c.Subcommands = append(c.Subcommands, helpCommandDontUse)
```
Comment (Dokiys) [inline help.go:242]: Why not create helpSubcommand here directly to avoid using?

**Review by Dokiys — APPROVED** [review]

File: help.go (hunk 1 above)
Comment (dearchap) [reply help.go:242]: We run in a recursion problem.
