### PR TITLE
Show non categorized flags with categorized on help

### LINKED ISSUE #1672: fix categorized flags alongside non categorized
## My urfave/cli version is

latest v2

## Checklist

- [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [X] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Describe the bug

Commit: https://github.com/urfave/cli/commit/8227be1fe9df91e3d69e17514df21b8e609d6cd0 
introduced a backward compatibility issue.  As before non categorized flags would show alongside categorized flags.  After this commit non categorized do not show at all.

## To reproduce

TestCommand_VisibleFlagCategories is a direct test of the breaking change, Just because no category is set, the flag should not be invisible.

## Expected behavior

Flags should show in help unless explicitly hidden

## Want to fix this yourself?

Sure, I'll introduce a PR shortly

## Run `go version` and paste its output here

```
go version go1.19.4 linux/amd64
```

### PR DESCRIPTION
**Pull request by skelouse**
## What type of PR is this?

- bug
- feature

## What this PR does / why we need it:

Reverting the removal of visible flags from help if their sibling flags have categories defined.

Example:
```
App:
    Flags:
        Flag1: // non categorized
        Flag2: Category1
        
Help Before PR:
    Options:
      Category1
        Flag2
        
Help After:
    Options:
        Flag1
      
      Category1
        Flag2
```

## Which issue(s) this PR fixes:

fixes #1672 

## Release Notes

```release-note
Reverted removal of non categorized flags alongside categorized flags
```

### CODE REVIEW

File: category.go [hunk 1]
```diff
@@ -100,10 +100,23 @@ func newFlagCategories() FlagCategories {
 
 func newFlagCategoriesFromFlags(fs []Flag) FlagCategories {
 	fc := newFlagCategories()
+
+	var categorized bool
 	for _, fl := range fs {
 		if cf, ok := fl.(CategorizableFlag); ok {
-			if cf.GetCategory() != "" {
-				fc.AddFlag(cf.GetCategory(), cf)
+			if cat := cf.GetCategory(); cat != "" {
```
Comment (dearchap) [inline category.go:107]: isnt this equivalent to ```fc.AddFlag(cf.GetCategory(), cf)``` with out the ```cf.getCategory() != "" ``` condition ?

**Comment by dearchap** [comment]
I think the main concern is whether empty string should be counted as a category. I am ok with either but it would be good if some stakeholders can chime in on this cc @urfave/cli

File: category.go (hunk 1 above)
Comment (skelouse) [reply category.go:107]: Yes, but then we're always working with categorized flags

Comment (dearchap) [reply category.go:107]: Ah ok got it.

**Review by dearchap — APPROVED** [review]

**Comment by skelouse** [comment]
v2.24.2?  @dearchap

**Comment by tarampampam** [comment]
@dearchap Apologies for the necroposting, but it seems that `v3.0.0-alpha7` still faces the same issue. At least, flags without categories are not printed when at least one flag has it. Could you please confirm this, and if so, could you create an issue to address this?

Or will it be better if I will do that?

/cc @jetexe
