### PR TITLE
Bug/fix issue 1703

### LINKED ISSUE #1703: CustomHelpTemplate is ignored with --help flag
## My urfave/cli version is

_**2.25.0**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is automatically downloading the latest version.

## Describe the bug

While `cli top-level-command help` respects `CustomHelpTemplate` when printing help, `cli top-level-command --help` ignores it and prints `SubcommandHelpTemplate` instead.

Is this intentional? What is the purpose of `SubcommandHelpTemplate`?

If this is not intentional i can send a PR switching to  `CustomHelpTemplate`

## To reproduce

```
app := cli.NewApp()
	app.Name = "testapp"
        app.Commands = []*cli.Command{
		        {
			        Name:   "top-level-command",
			        Action: func(c *cli.Context) error { return nil },
			        CustomHelpTemplate: "TESTING",
			 }
}
```

```
go run ./cmd/app top-level-command --help
```

## Observed behavior

It prints `SubcommandHelpTemplate`

## Expected behavior

`go run ./cmd/app top-level-command --help` should print `CustomHelpTemplate`

## Additional context

https://github.com/temporalio/cli/pull/153

## Want to fix this yourself?

**Yes**

## Run `go version` and paste its output here

go version

### PR DESCRIPTION
**Pull request by jojje**
## What type of PR is this?

- bug

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

fixes #1703

## Special notes for your reviewer:

Let me know if you want the solution somewhere else in the code-base.

I noticed that you try to contain corner case handling to the `helpCommand.Action` callback. However I'm not familiar enough with the code-base to fully understand what the right set of conditions would be by comparing various disparate but seemingly interconnected objects and fields/attributes.

Instead I went for the most intuitive solution of simply ensuring that whenever the help command is about to be rendered, instead of assuming that the caller has populated the cCtx correctly, I used _defensive programming_ to ensure honoring the intent of using a custom template for given command, at the closest location to the template use, if the command happens to have one defined.

## Testing

Two unit tests added. One for the happy path to ensure the behavior didn't change in that regard. The other for the error path which triggers the bug and which this fix addresses.

tests were performed by running `make test`

## Release Notes

_(REQUIRED)_

```release-note
* Custom help templates are now used when -h[elp] flag is given, even when no sub-commands are defined. 
```

### CODE REVIEW

File: help_test.go [hunk 1]
```diff
@@ -1126,6 +1126,61 @@ func TestHideHelpCommand_WithSubcommands(t *testing.T) {
...
+func TestHideHelpCommand_RunAsSubcommand_False_CustomTemplate(t *testing.T) {
+	var buf bytes.Buffer
+
+	app := &App{
+		Writer: &buf,
+		Commands: []*Command{
+			{
+				Name:               "dummy",
+				CustomHelpTemplate: "TEMPLATE",
+				HideHelpCommand:    false,
```
Comment (dearchap) [inline help_test.go:1138]: This is redundant since default is false.

**Review by dearchap — APPROVED** [review]

**Comment by dearchap** [comment]
@jojje Thanks for your PR. I've changed the merge from main to v2-maint.

File: help.go [hunk 2]
```diff
@@ -77,10 +78,25 @@ var helpCommand = &Command{
...
+			for _, c := range candidates {
+				if c == alias {
+					return true
+				}
+			}
+		}
+	}
+	return false
+}
+
```
Comment (meatballhat) [inline help.go:99]: I can't find where this function is used 🤔

Comment (jojje) [reply help.go]: Oh, that should never have made it into the PR.
It was a different approach to solving the problem. Thanks for spotting this Dan!

Pushed a corrective commit that removes this function, and also the redundant test which DC pointed out.
Once you're happy, I'll squash the PR.

**Review by dearchap — APPROVED** [review]
